// <auto-generated />
using System;
using Helsinki.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helsinki.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Helsinki.Domain.Entities.ConversionHistory", b =>
                {
                    b.Property<Guid>("ConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConversionDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRate")
                        .HasPrecision(18, 9)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FromAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConversionId");

                    b.HasIndex("ConversionDate");

                    b.HasIndex("UserId");

                    b.ToTable("Conversions");
                });
#pragma warning restore 612, 618
        }
    }
}
